### ISSUE TITLE
Error creating pcm task as user

### ISSUE THREAD

**Issue by beyossi** [intelsdi-x/snap-plugin-collector-pcm#32]
hello. I have a problem with tasks using pcm collector.
I have two machines with exactly the same configuration: CPU E5-2699 v4 @ 2.20GHz, ubuntu 16.04
snapd version 0.18.0
snap-plugin-collector-pcm version 9
Linux ben1 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I am following same procedure on both machines and in one machine I can load pcm plugin and  create pcm task, while on the other machine i can load the pcm but fail to create task due to: "Error creating task:error starting plugin: timed out waiting for plugin snap-plugin-collector-pcm".
pcm.x works well.

the fail log:
```
time="2017-01-25T13:30:06+02:00" level=info msg="validating dependencies for plugin rabbitmq:-1" _block=validate-plugin-subscription _module=control plugin="rabbitmq:-1"
time="2017-01-25T13:30:06+02:00" level=info msg="finding latest plugin" _module=control-plugin-mgr
time="2017-01-25T13:30:06+02:00" level=info msg="validating dependencies for plugin pcm:9" _block=validate-plugin-subscription _module=control plugin="pcm:9"
time="2017-01-25T13:30:06+02:00" level=info msg="task created" _block=create-task _module=scheduler source=user start-on-create=true task-id=6faf4bb7-ca81-466b-8a91-11a082f9bc0d task-state=Stopped
time="2017-01-25T13:30:06+02:00" level=info msg="starting task on creation" _block=create-task _module=scheduler source=user start-on-create=true task-id=6faf4bb7-ca81-466b-8a91-11a082f9bc0d
time="2017-01-25T13:30:06+02:00" level=info msg="finding latest plugin" _module=control-plugin-mgr
time="2017-01-25T13:30:06+02:00" level=info msg="finding latest plugin" _module=control-plugin-mgr
time="2017-01-25T13:30:11+02:00" level=error msg="error starting a plugin" _block=start-plugin _module=control-runner error="error starting plugin: timed out waiting for plugin snap-plugin-collector-pcm"
time="2017-01-25T13:30:11+02:00" level=error msg="error starting new plugin" _block=run-plugin _module=control-runner error="error starting plugin: timed out waiting for plugin snap-plugin-collector-pcm" path="/tmp/666162486/snap-plugin-collector-pcm" 

note that I am using it as user and not root after following the procedure:
sudo ln -s /usr/workspace/pcm_plugin_execs/pcm.x /usr/bin/pcm.x
sudo modprobe msr
sudo chmod 777 /dev/cpu/*/msr
sudo setcap cap_sys_rawio=ep /usr/workspace/pcm_plugin_execs/pcm.x
sudo su
echo 'kernel.nmi_watchdog=0' >> /etc/sysctl.conf
echo 0 > /proc/sys/kernel/nmi_watchdog
echo "-1" > /proc/sys/kernel/perf_event_paranoid
exit
```

is there a known issue or is it a kind of misconfiguration of my system?

**Comment by katarzyna-z** [comment]
It seems that your procedure is ok. To better understanding of the issue I would like to ask you for more information.
Could you check if pcm is working on the second machine? Please execute `./pcm.x /csv=file.csv`. Could you share file.csv?
Could you share your task manifest? Could you also check if longer "interval" in the task manifest enables collection of metrics?

**Comment by beyossi** [comment]
Thanks @katarzyna-z .
attached are host1 and host2 (both in csv format).
for some reason i cannot load the plugin anymore at none of my hosts, not even with snapd using --plugin-load-timeout 12. they fail with "timed out waiting for plugin snap-plugin-collector-pcm".

anyway i attached also the task manifest. i tried it with 10 seconds as well.

[ben1_L0_pcm.json.txt](https://github.com/intelsdi-x/snap-plugin-collector-pcm/files/739153/ben1_L0_pcm.json.txt)
[host1.csv.txt](https://github.com/intelsdi-x/snap-plugin-collector-pcm/files/739140/host1.csv.txt)
[host2.csv.txt](https://github.com/intelsdi-x/snap-plugin-collector-pcm/files/739139/host2.csv.txt)

**Comment by katarzyna-z** [comment]
@beyossi  I observed the similiar behaviour of the plugin when pcm.x was not found in the $PATH. 
I'm using the latest version of Snap and pcm plugin, please see:
- https://github.com/intelsdi-x/snap/releases
- https://github.com/intelsdi-x/snap-plugin-collector-pcm/releases

Please do these simple steps:
in one terminal window:
```
$ sudo su
$ export PATH=$PATH:<your_path_to_dir_with_pcm.x>
$ snapteld -l 1 -t 0
```
in another terminal window:
```
$ sudo su
$ export PATH=$PATH:<your_path_to_dir_with_pcm.x>
$ snaptel plugin load snap-plugin-collector-pcm
```

**Comment by beyossi** [comment]
@katarzyna-z 
exporting updated PATH didn't work for me, though it worked when i copied the entire <path_to_dir_with_pcm.x> to /usr/bin

the snap log file indicated that the PCM couldn't be found and suggested to update the PATH, however it was already updated and i could execute successfully pcm.x from the shell.
I have to admit that i can't understand why snap couldn't find it, but copying them all to /usr/bin worked ...... so i am happy :)

Thanks!
