### ISSUE TITLE
Unable to load PCM plugin

### ISSUE THREAD

**Issue by rehank30** [intelsdi-x/snap-plugin-collector-pcm#44]
When trying to load pcm plugin it shows this error:
GetMetricTypes call error: exec: "pcm.x": executable file not found in $PATH

**Comment by AbhiPandey1** [comment]
@rehank30 were you able to resovle this issue?

**Comment by IzabellaRaulin** [comment]
hello @rehank30, please check the following:
a) **pcm is installed on your machine**
Follow the instruction available at http://www.intel.com/software/pcm
b) **NMI watchdog is disabled**
To disable it permanently, run ```echo 'kernel.nmi_watchdog=0' >> /etc/sysctl.conf```
c) **Allow accessing CPUs Model Specific Registers (MSRs**
Execute 'modprobe msr' as root user

To be sure that pcm.x works properly, try to execute ```pcm.x  -nc -r 1```

Then run Snap and load the snap-plugin-collector-pcm - and let me know if it's loaded properly.
